name: Daily Stock Price

on:
  workflow_dispatch: 
  schedule:
    # 设定在每周一至周五的 北京时间下午 15:15 自动运行 (UTC 07:15)
    - cron: '15 7 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        # 将 GitHub Secrets 映射到环境变量
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python main.py
